### ISSUE TITLE
Match/Round callbacks

### ISSUE THREAD

**Issue by geminax** [MrOkiDoki/BattleBit-Community-Server-API#11]
Hi,

I want to do more detailed stat tracking, generating reports after rounds/matches. There don't seem to be any match or round related callbacks, such as:

`OnMatchStart`
`OnMatchFinish`
`OnRoundStart` 
`OnRoundFinish`

Could probably condense these, but all I think I would need is the GameServer passed back.

**Comment by No-Half-Measures** [comment]
Agreed, I'd like to do a similar thing needing these. But the callbacks would open other use cases too such as; Random Game Modifiers each match or a team balance system based on a custom MMR system, I think you get the idea of how useful these callbacks are.

**Comment by aleDsz** [comment]
Would be cool to have the match ID for these callbacks, so it would make it easy to store the match report and track all the data about it.

```
OnMatchStart: Return the Match ID
OnRoundStart: Return the Round ID, in addition of Match ID
OnRoundFinish: Return the Round ID and the Round report for each player
OnMatchFinish: Return the Match ID and the Match report (summarized round reports)
```

This could make a way to generate a Match report and each Round report. I can see a use case for this, with competitive matches (GvG/mix).

**Comment by geminax** [comment]
Added

**Comment by geminax** [comment]
I'm not going to reopen this, but I'd like to point out that this doesn't really "work" for Rush rounds in the way that I would like it to, but I realize this is no fault of the API, but rather how the Rush gamemode itself is implemented. It seems to start a whole other match _rather than_ saving stats, moving everybody to the opposite side, and resetting the bomb site progression
 
So, hopefully Rush is improved a bit and then in an ideal world, the round callbacks would behave accordingly to rush rounds. Currently, if I wanted to save stats for a rush match (both sides), it's totally possible, but just more work on our end. @MrOkiDoki
