### ISSUE TITLE
[Feature Request] Event args

### ISSUE THREAD

**Issue by moddedmcplayer** [MrOkiDoki/BattleBit-Community-Server-API#13]
Heres an example: Instead of `OnDamagedPlayer(Player player, Player attacker, (ref) float damage)`, use `OnDamagedPlayer(OnDamagedPlayerArgs ev)` where
```
public class OnDamagedPlayerArgs
{
    public Player Player { get; }
    public Player Attacker { get; }
    public float Damage { get; set; }
}
```
You could also include a `bool Cancel { get; set; }` for cancelling instead of using return values, which allows for other event handler to interact with already cancelled events. Similarly you can also use the set accessors to change variables such as damage without needing to declare variables as `ref`.

**Comment by nurdism** [comment]
I feel like this would add way too much latency, you got to remember this is an _external_ api that is sent to a separate program via a TCP connection, if `OnDamagedPlayer` where to be added, every single time a player gets hit, it (the game server) would then have to send a packet to the api server then the api server would have to respond with an 👍or a 👎witch even with 0 ping, on the same hardware (server box) would at least take a few ms for the round trip, then times that by up to 250+ players and thats a loooooot of latency. 

For something like this to work, you'd need to enable some kinda modding api and the game server itself would need to be able to load external code

**Comment by moddedmcplayer** [comment]
> I feel like this would add way too much latency, you got to remember this is an _external_ api that is sent to a separate program via a TCP connection, if `OnDamagedPlayer` where to be added, every single time a player gets hit, it (the game server) would then have to send a packet to the api server then the api server would have to respond with an 👍or a 👎witch even with 0 ping, on the same hardware (server box) would at least take a few ms for the round trip, then times that by up to 250+ players and thats a loooooot of latency.
> 
> For something like this to work, you'd need to enable some kinda modding api and the game server itself would need to be able to load external code

'Heres an example:'

**Comment by MapleEve** [comment]
> > I feel like this would add way too much latency, you got to remember this is an _external_ api that is sent to a separate program via a TCP connection, if `OnDamagedPlayer` where to be added, every single time a player gets hit, it (the game server) would then have to send a packet to the api server then the api server would have to respond with an 👍or a 👎witch even with 0 ping, on the same hardware (server box) would at least take a few ms for the round trip, then times that by up to 250+ players and thats a loooooot of latency.
> > For something like this to work, you'd need to enable some kinda modding api and the game server itself would need to be able to load external code
> 
> 'Heres an example:'

This is good if some args are updated. Anyway, the other fork uses too many new DB connections and maybe not stable.

**Comment by moddedmcplayer** [comment]
> > > I feel like this would add way too much latency, you got to remember this is an _external_ api that is sent to a separate program via a TCP connection, if `OnDamagedPlayer` where to be added, every single time a player gets hit, it (the game server) would then have to send a packet to the api server then the api server would have to respond with an 👍or a 👎witch even with 0 ping, on the same hardware (server box) would at least take a few ms for the round trip, then times that by up to 250+ players and thats a loooooot of latency.
> > > For something like this to work, you'd need to enable some kinda modding api and the game server itself would need to be able to load external code
> > 
> > 
> > 'Heres an example:'
> 
> This is good if some args are updated. Anyway, the other fork uses too many new DB connections and maybe not stable.

wdym?

**Comment by MapleEve** [comment]
> 

not related to concurrent fork PR, it's from @muji2498 's work,

**Comment by Blamudia** [comment]
Wouldn't it be better to use CancellationTokens? they're pretty much meant for these types of scenario's
https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken?view=net-6.0

**Comment by moddedmcplayer** [comment]
> Wouldn't it be better to use CancellationTokens? they're pretty much meant for these types of scenario's https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken?view=net-6.0

CancellationTokens are mainly used for async Tasks that can be cancelled anytime during its  execution, among other things. There is no advantage to using them over a simple bool in this scenario.
Either way, this is independent of whether or not your using event arguments. Its a decision up to the implementation itself.

**Comment by moddedmcplayer** [comment]
New system is good enough for me.
