### ISSUE TITLE
[Feature Request] OnPlayerConnected/OnGetPlayerStats return IP Address

### ISSUE THREAD

**Issue by henrik9999** [MrOkiDoki/BattleBit-Community-Server-API#16]
so its possible to implement IP bans for example

**Comment by moddedmcplayer** [comment]
> so its possible to implement IP bans for example

I would prefer having an IP property on the `Player` class.

**Comment by henrik9999** [comment]
> > so its possible to implement IP bans for example
> 
> I would prefer having an IP property on the `Player` class.

That is an option as well

**Comment by the-eduardo** [comment]
If possible it would be rally helpful
