### ISSUE TITLE
[Feature Request] Voxel world modification

### ISSUE THREAD

**Issue by fuzzbuck** [MrOkiDoki/BattleBit-Community-Server-API#18]
Would love to see implementation of packets for directly reading & writing to the Voxel world to allow for direct map modification
(adding & removing voxels)

i.e
(Server -> API)
OnWorldSpawn(voxels: Voxel[]);
OnVoxelBuild(voxel, playerl); (cancellable)
OnVoxelDestroy(voxe;, player); (cancellable)

(API -> Server)
CreateVoxel(x, y);
DestroyVoxel(x, y);

Voxel {
    x: int,
    y: int,
    ... additonal data
}

**Comment by MapleEve** [comment]
Actually, please add Z layer for that.

**Comment by moddedmcplayer** [comment]
> Actually, please add Z layer for that.

`UnityEngine::Vector3` is probably what you are looking for.

**Comment by MrOkiDoki** [comment]
Those were added.

`GameServer.PlaceVoxelBlock(player.Position, new VoxelBlockData() { TextureID = VoxelTextures.NeonOrange });
GameServer.DestroyVoxelBlock(player.Position);`
