### ISSUE TITLE
Handling Multiple Server Subclasses under one Listener

### ISSUE THREAD

**Issue by geminax** [MrOkiDoki/BattleBit-Community-Server-API#25]
With the advertisement and expected behavior of the API being able to handle multiple servers, I don't believe there is any direct support for handling different GameServer/Player subclasses. Currently, we template the ServerListener with the subclass we want, and if we make another GameServer/Player subclass pair, it seems the only way would be to create another ServerListener.

I don't know what the alternative is, but this seems unoptimal. Perhaps we can delegate the subclass we want in the GameServerConnected/Reconnected callbacks (this is probably not possible since it's essentially a downcast)? I'm not sure of the magic involved for this, but it would be nice, unless there's another alternative I'm not aware of.

**Comment by Mooshua** [comment]
> (this is probably not possible since it's essentially a downcast)?

That’s what virtuals and interfaces are for.

Ultimately I think the API is better as a single tenant system—individuals and groups can then build stuff on top that works best for them. Creating a one-thing-fits-all is extremely difficult, especially when it comes to game modding.

That way, developers and communities can converge on the designs that work best for them—instead of being forced into something that may be an awkward or less than ideal design for their use case.

**Comment by geminax** [comment]
> That’s what virtuals and interfaces are for.

C# is not my area but still, in the api's current design, there is no way that I can see that allows me to change the server callbacks at runtime. A solution would perhaps be allowing us to define and choose our interface on the go as game servers connect, but I digress.

> Ultimately I think the API is better as a single tenant system—individuals and groups can then build stuff on top that works best for them. Creating a one-thing-fits-all is extremely difficult, especially when it comes to game modding.\n\nThat way, developers and communities can converge on the designs that work best for them—instead of being forced into something that may be an awkward or less than ideal design for their use case.

Good point. I agree this would complicate things. I was under the impression this was intended for this, but theres no reason why I can't implement this design myself.

**Comment by geminax** [comment]
Closing
