### ISSUE TITLE
Fix namespacing, current code does not compile

### ISSUE THREAD

**Issue by Julgers** [MrOkiDoki/BattleBit-Community-Server-API#37]
See https://github.com/MrOkiDoki/BattleBit-Community-Server-API/actions/runs/5877621581/job/15938085115

**Comment by moddedmcplayer** [comment]
Just remove the usings.

**Comment by Julgers** [comment]
Closing as fixed per commit [`7f8ee71`](https://github.com/MrOkiDoki/BattleBit-Community-Server-API/commit/7f8ee714cb77cea1fce06d2a9c12177428daffdd).
