### ISSUE TITLE
[bug] GameServer FixedSize

### ISSUE THREAD

**Issue by geminax** [MrOkiDoki/BattleBit-Community-Server-API#39]
I am not aware of the exact issue here since I do not have the Game Server code, but if I set `FixedSize=none` or not at all in the server start arguments, and try to play with map/gamemode rotations and end the game, the voting screen is empty, can't vote for anything, counter goes down to 1, and nothing happens except the continuous zoom out. The server starts spamming null reference exceptions:

![image](https://github.com/MrOkiDoki/BattleBit-Community-Server-API/assets/59982021/76ec1e7c-e51a-42ad-adb0-c1cc92cb22a0)

This could perhaps be due to incompatibilities with the scale/gamemode/map selections, but the server should surely be able to handle these cases and others, so that this doesn't happen.

**Comment by MrOkiDoki** [comment]
This is happening because game server is unable to find map/gamemode to your requirements which fails to pass to next map.
