### ISSUE TITLE
[bug] Player.HP not being updated

### ISSUE THREAD

**Issue by geminax** [MrOkiDoki/BattleBit-Community-Server-API#40]
I have a command that is supposed to check if the player is alive before further processing. When a player is spawned in, they type a command, and the `IsAlive` property is still false. I see that this property depends on HP >=0. I checked this property as well. It is still at -1 when a player is alive.

**Comment by No-Half-Measures** [comment]
Currently the Community-Testing branch it out of date and as such some of the new variables avalible to use aren't currently functional.
Can check [steamdb.info](https://steamdb.info/app/671860/depots/?branch=community-testing) and scrol down to branches to see when the branch was last updated
