### ISSUE TITLE
[Bug] Gameserver doesn't seem to know what RUSH is

### ISSUE THREAD

**Issue by No-Half-Measures** [MrOkiDoki/BattleBit-Community-Server-API#41]
**Description:**
Trying to append the 'RUSH' gamemode to the gamemode rotation results in the server (not the API) returning `Unable to convert gamemode of RUSH` 

**Reproduction**
Add the following into the `GameServer.OnConnected` callback:
```csharp
GamemodeRotation.AddToRotation("RUSH");
GamemodeRotation.AddToRotation("RS");
GamemodeRotation.AddToRotation("rush");
GamemodeRotation.AddToRotation("rs");
```

**Expected Behavior**
For the 'RUSH' gamemode to be added to the rotation with no server error of not bneing able to covert the gamemode.

**Result**
This is the Gameservers responce:
![image](https://github.com/MrOkiDoki/BattleBit-Community-Server-API/assets/916733/50b841a3-a7f1-4473-9a84-0a92585ca3b5)

**Comment by MrOkiDoki** [comment]
Fixed on new build, 'RUSH' will work.
