### ISSUE TITLE
[Bug] Player.Message cuts 1 character off the string

### ISSUE THREAD

**Issue by Pelayori** [MrOkiDoki/BattleBit-Community-Server-API#52]
**Describe the bug**
When using Player.Message, the message shown has 1 character stripped from the end of the string

**To Reproduce**
1. Send a message to a player trough Player.Message

**Expected behavior**
The message should be shown as it was sent from the API

**Screenshots**
![image](https://github.com/MrOkiDoki/BattleBit-Community-Server-API/assets/31128562/4c6d5792-63e2-42d9-84f8-966baec2533f)
![image](https://github.com/MrOkiDoki/BattleBit-Community-Server-API/assets/31128562/0cfb980f-415e-4748-adf4-8e1eb0695254)

**Comment by MrOkiDoki** [comment]
Fixed on new version

**Comment by MrOkiDoki** [comment]
Fixed on new version
