### ISSUE TITLE
Multiple GameServers on one ip have same ServerHash

### ISSUE THREAD

**Issue by muji2498** [MrOkiDoki/BattleBit-Community-Server-API#6]
Steps to reproduce:
- Make mActiveConnections public(is this bad practice lmao)
- Create Two GameServers with same ip but different port number
- add the two GameServers to the mActiveConnections Dictionary.

Obviously I don't have access to the game build with api support so to simulate multiple gameservers I created two GameServer objects

![image](https://github.com/MrOkiDoki/BattleBit-Community-Server-API/assets/19718787/172a6fff-8d6a-4fa0-bac1-05abe8ec5f70)
^^ Is this supposed to be intentional?

If each of the servers were to have different IPs then you can place them in the dictionary.
![image](https://github.com/MrOkiDoki/BattleBit-Community-Server-API/assets/19718787/ccd08994-f016-4d1d-b558-c1df1220fa0f)

P.S. ignore the ugly console output formatting lol

**Comment by geminax** [comment]
I believe the root issue is that the cast to 64 bits is misplaced:
```diff
diff --git a/BattleBitAPI/Server/GameServer.cs b/BattleBitAPI/Server/GameServer.cs
index 095fad0..cf9ab9f 100644
--- a/BattleBitAPI/Server/GameServer.cs
+++ b/BattleBitAPI/Server/GameServer.cs
@@ -94,7 +94,7 @@ namespace BattleBitAPI.Server
             this.mLastPackageReceived = Extentions.TickCount;
             this.mLastPackageSent = Extentions.TickCount;
 
-            this.ServerHash = (ulong)(port << 32) | iP.ToUInt();
+            this.ServerHash = ((ulong)port << 32) | iP.ToUInt();
         }
 
         // ---- Tick ----

```
