### ISSUE TITLE
[Feature Request] `ForceEndGame` overload with winning team

### ISSUE THREAD

**Issue by Pelayori** [MrOkiDoki/BattleBit-Community-Server-API#64]
**Is your feature request related to a problem? Please describe.**
Usually I want to declare a winning team no matter the tickets, and setting them is quite unreliable due to calling force end game and the tickets are as they would be in a vanilla server, they don't seem to get affected if you call end game after setting them

**Describe the solution you'd like**
An overloaded (or optional parameter) `ForceEndGame` version would let us decide the winning team without any further issue

**Describe alternatives you've considered**
Changing the losing team's tickets to 0, and the other one to a higher number > 0

**Additional context**
Changing team tickets used to work, until one of the recent update it no longer worked. I used a Task delay after the game was declared finished by my game mode implementation, but no luck there either.

**Comment by MrOkiDoki** [comment]
This is added on new update (1.0.6v)

`var list = new List<EndGamePlayer<MyPlayer>> ();
list.Add(new EndGamePlayer<MyPlayer>(player, 12345));
list.Add(new EndGamePlayer<MyPlayer>(player, 236526));
list.Sort();
GameServer.ForceEndGame(list);`

or

`player.GameServer.ForceEndGame(Team.TeamA); //Team a wins!`
