### ISSUE TITLE
[Bug] Unable to connect to API when restarting the server while players are connected

### ISSUE THREAD

**Issue by RainOrigami** [MrOkiDoki/BattleBit-Community-Server-API#66]
**Describe the bug**
When restarting a game server with a connected API while there are players on the server, the new game server instance will spam
```
API: Unable to connect to API server: Object reference not set to an instance of an object.
```
until the API is restarted.

**To Reproduce**
1. Start server and API, order does not matter
2. Connect a client to the server
3. Restart the server by quickly closing and reopening
4. If the server starts before the client is being disconnected, the error will occur

**Expected behavior**
The server should successfully reconnect and the client should probably not stay connected if the server is restarted.

**Screenshots**
https://www.youtube.com/watch?v=8lVF8pOIKrU

**Additional context**
Tested with simple community server API implementation, not using the modules runner.
It seems that the player, who was connected to the previous server, is still connected in the new server and will mess up the communication between the server and the API. The exception occurs at Player.cs in the getter of Squad because GameServer is null for this player.

**Comment by MapleEve** [comment]
It seems that, when an instance of GameServer disconnects in Socket, You must release its MyPlayer and/or MyGameserver usage, or it will mess the memory address.

**Comment by MrOkiDoki** [comment]
Fixed on new update.
