### ISSUE TITLE
[Bug] When next map == curMap with the same mode. Server freeze.

### ISSUE THREAD

**Issue by MapleEve** [MrOkiDoki/BattleBit-Community-Server-API#67]
**Describe the bug**
Currently I use my RNG to randomly choose a next map (in config) when a new round begins.

```csharp
public override async Task OnGameStateChanged(GameState oldState, GameState newState)
                case GameState.Playing:
                        this.MapRotation.ClearRotation();
                        var nextMap = MapManager.GetARandomAvailableMap(Gamemode, Map);
                        this.MapRotation.SetRotation(nextMap);
```

As a test result, if you dont remove cur `Map` from that result array, the game will freeze in map votes.

**To Reproduce**
As the code above presented.

**Expected behavior**
Should we allow player to play a same map after this round?
If it shoudn't I've alter the `GetARandomAvailableMap` function to opt in a `Map` and it will RNG other maps.

**Screenshots**
Sorry, this I just remembered the MapVote list is blank and when Endgame countdown hits zero, nothing happened.
When you quit the server and rejoin, received ERR CODE:1. the server prints 6000ms timeout.

**Additional context**
N/A
Should be easy to reproduce.

**Comment by MapleEve** [comment]
![image](https://github.com/MrOkiDoki/BattleBit-Community-Server-API/assets/1845053/cc836633-498c-447b-b133-5c69eb973e61)

**Comment by MapleEve** [comment]
One more thing, the GameServer.Map is not represent the current map name.
So if I just remove the Map and then it removes the first map, not the current map
```csharp
        public static string somefunction (string currentMode, string currentMap)
        {
            List<string> mapList = GetAvailableMapList(currentMode);
            if (mapList.Contains(currentMap))
                mapList.Remove(currentMap);
            int rng = RandomNumberGenerator.GetInt32(mapList.Count);
            return mapList[rng];
        }
```
Code above shows how I get a random next map.

**Comment by Julgers** [comment]
Apparently fixed

**Comment by henrik9999** [comment]
> One more thing, the GameServer.Map is not represent the current map name. So if I just remove the Map and then it removes the first map, not the current map
> 
> ```cs
>         public static string somefunction (string currentMode, string currentMap)
>         {
>             List<string> mapList = GetAvailableMapList(currentMode);
>             if (mapList.Contains(currentMap))
>                 mapList.Remove(currentMap);
>             int rng = RandomNumberGenerator.GetInt32(mapList.Count);
>             return mapList[rng];
>         }
> ```
> 
> Code above shows how I get a random next map.

https://github.com/MrOkiDoki/BattleBit-Community-Server-API/issues/62 for that
