### ISSUE TITLE
OnAPlayerKilledAnotherPlayer callback missing headshot

### ISSUE THREAD

**Issue by jesseyvanofferen** [MrOkiDoki/BattleBit-Community-Server-API#7]
I'm currently working on creating a database and store statistics in here such as linking usernames to steamID's and user reports etc, but I would also like to store the statistics about headshots but the callback OnAPlayerKilledAnotherPlayer only has the distance and weapon. I would like to see this being added so I can automatically flag players which have an insane amount of headshots compared to body kills.

**Comment by MrOkiDoki** [comment]
Could you make a list?

**Comment by jesseyvanofferen** [comment]
@MrOkiDoki In my case I pretty much only care about a boolean true|false being passed along. The idea of @muji2498 would be a nice suggestion, and it can then pass along a string just like how the reporting reason works.

**Comment by MrOkiDoki** [comment]
Any further requests? I will implement the body hits, other than that any?
