### ISSUE TITLE
[Bug] wild coordinates

### ISSUE THREAD

**Issue by mevenG** [MrOkiDoki/BattleBit-Community-Server-API#74]
**Describe the bug**
Kill coordinates are not the same as spectate coordinates in the same place

**To Reproduce**
die, the api `OnPlayerKillArguments` tells `[ 570.96204, 304.9897, 497.32202 ]`.
spectate and go to the same place =>`[ 71, 56, -3,2 ]`

**Expected behavior**
I don't know, maybe give same coords ? 0.0

**Screenshots**
![BattleBit_PNWvyQshKN](https://github.com/MrOkiDoki/BattleBit-Community-Server-API/assets/110609130/d5264293-d996-463a-8ca0-3e9dd0c97bc1)

**Comment by RainOrigami** [comment]
This is also related to an issue where the OnPlayerSpawnArguments.SpawnPosition coordinates differ wildly from the actual player coordinates after the player has spawned.

Are there two different coordinate systems in place that need to be translated somehow?

**Comment by MapleEve** [comment]
It's client side Vector3 and server side Vector3.
I've report it as a bug.

**Comment by MapleEve** [comment]
Just tested, Fixed in 2.1.0
