### ISSUE TITLE
[Feature Request] OnPlayerDie include pos, tool, killer and headshot

### ISSUE THREAD

**Issue by nurdism** [MrOkiDoki/BattleBit-Community-Server-API#9]
I'd like to be able to see more info about the payers death other than a steamId

**Comment by MrOkiDoki** [comment]
Could you send a list of things you want to add to the callback?

**Comment by nurdism** [comment]
actually thinking about it, is there a difference between `OnPlayerDie` and `OnPlayerKilledAnotherPlayer` @MrOkiDoki? `OnPlayerDie` could be called from `OnPlayerKilledAnotherPlayer` with 

```
killerSteamId = UInt64
killerPosition = [float, float, float]
victimSteamId = UInt64
victimPosition = [float, float, float]
tool = string
isHeadshot = bool

call OnPlayerKilledAnotherPlayer(killerSteamId, killerPosition, victimSteamId, victimPosition, tool, isHeadshot)

call OnPlayerDie(victimSteamId, victimPosition, tool, isHeadshot, killerSteamId, killerPosition )
victim.Alive = false```

**Comment by nurdism** [comment]
oh but what if there is no player that kills, maybe `OnPlayerDie` could have nullable `killerPosition`, `killerSteamId` and you could just remove `OnPlayerKilledAnotherPlayer`

so something like 
```killerSteamId = UInt64  (0 for no one)
killerPosition = [float, float, float] ([0,0,0] for no one)
victimSteamId = UInt64
victimPosition = [float, float, float]
tool = string (empty for no one)
isHeadshot = bool

call OnPlayerDie(victimSteamId, victimPosition, tool, isHeadshot, killerSteamId?, killerPosition?)
```

**Comment by MrOkiDoki** [comment]
OnPlayer die could be anything, suicide, server killing the player, gamemode killing the player etc.

**Comment by nurdism** [comment]
Yes, I was thinking out loud, `OnPlayerDie` could include a nullable `tool `, `killerPosition` & `killerSteamId` instead of having 2 separate hooks/callbacks `OnPlayerKilledAnotherPlayer` and `OnPlayerDie`. You could still have a `OnPlayerKilledAnotherPlayer` callback but could be called from `OnPlayerDie` instead of from the server directly

**Comment by moddedmcplayer** [comment]
> Yes, I was thinking out loud, `OnPlayerDie` could include a nullable `tool `, `killerPosition` & `killerSteamId` instead of having 2 separate hooks/callbacks `OnPlayerKilledAnotherPlayer` and `OnPlayerDie`. You could still have a `OnPlayerKilledAnotherPlayer` callback but could be called from `OnPlayerDie` instead of from the server directly

DamageHandler which gets inherited by PlayerDamageHandler, SuicideDamageHandler, etc.

**Comment by aleDsz** [comment]
The player position could be the [´Point3D` class](https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.media3d.point3d).

We can take the structure of [`Kill` class from `PRoCon` project](https://github.com/AdKats/Procon-1/blob/5ef254d680acf8ae5b1c2e8691ec3c25a9c8792a/src/PRoCon.Core/Kill.cs)

**Comment by moddedmcplayer** [comment]
> The player position could be the [´Point3D` class](https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.media3d.point3d).
> 
> We can take the structure of [`Kill` class from `PRoCon` project](https://github.com/AdKats/Procon-1/blob/5ef254d680acf8ae5b1c2e8691ec3c25a9c8792a/src/PRoCon.Core/Kill.cs) as inspiration

Im not a big fan of the namespace `System::Windows::Media::Media3D::Point3D` is in.
I suggest for sake of consistency to use `System::Numerics::Vector3``
